(clear)
(printout t "---NEW-------------------------------" crlf)
(load "headers.clp")
(load "MAIN-rules.clp")
(load "PERCEPT-MANAGER.clp")
(load "AddMomentBelifsGetStartTime.clp")
; (load "./agenti/DRIVER-AGENT1.clp")
; (load "./agenti/DRIVER-AGENT2.clp")
(load "./agenti/DRIVER-AGENT3.clp") 
(load "TellDeleteMomentBelifsGetEndTime.clp")
(load "initials.clp")
(load "maneuverValidityASK.clp")
(reset)
(bind ?t (time))
(run ?*totalNrRules*)
(printout t "INFERENCE TIME: " (- (time) ?t) crlf)
